In [1]:
import numpy as np

In [2]:
#Criar matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [6]:
#Criar array de tipo especifico
#Cria array como float de 64 bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([4,5,6], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


In [8]:
#Mudar o tipo de array
#Podemos transformar tipos de dados de array
mtnew = np.array([1.3,3.5,-8.8,9.46,3.99])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.3   3.5  -8.8   9.46  3.99]
[ 1  3 -8  9  3]


In [9]:
#Podemos fazer o inveso também
mt5 = np.array([1,2,3,4,5])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [10]:
#Mais de uma dimensão
#Criar matris bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,26]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 26]]


In [14]:
#Criar arrays vazios tipificados
#Empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("------")
#Cria uma matrix 4x3 com valores zero
zero = np.zeros([4,3])
print(zero)
print("------")
#Com valores igual a um
um = np.ones([5,7])
print(um)
print("------")
#Criar matriz quadrada com diagonal principal com valores 1 e outros valores 0
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
#Valores aleatórios entre zero e um
ale = np.random.random((1))
print(ale)
print("------")
#Valores aleatórios distribuição normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("------")
#Valores aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.50877128]
------
[ 0.51430875  0.61503472  0.00768874  0.0681585  -0.50993898]
------
[[3.46906677 9.71269975 1.31953487 7.13082205]
 [8.61719637 1.23422021 7.46194682 0.95939783]
 [3.02490376 6.04605882 7.08133581 4.81568442]]


In [33]:
#Outra forma de gerar números aleatórios
#Uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
#Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [34]:
#Unique remove repetições
j = np.array([11,12,13,14,15,12,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 18 19 20]


In [37]:
#Funcões especificas
#Cria matriz bidimensional k
k = np.array([[17,22,43],[27,25,13],[15,24,32]])
#Mostra matriz k
print(k)
#Mostra elemento especifico da matriz k
print(k[0][1])
#Mostra o tamanho da dimensão da matriz k
print(k.shape)

[[17 22 43]
 [27 25 13]
 [15 24 32]]
22
(3, 3)


In [38]:
#Funções matemáticas
#Mostra o maior valor da matriz k
print(k.max())
#Mostra o menor valor da matriz k
print(k.min())
#Mostra a soma dos valores da matriz k
print(k.sum())
#Mostra o valor da média dos valores da matriz k
print(k.mean())
#Mostra o valor do desvio padrão (Standard Deviation) dos valores da matriz k
print(k.std())

43
13
218
24.22222222222222
8.75312995165828


In [39]:
#Funcões universais, aplicadas a todos os elementos
#Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))
#Mostra o valor exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [41]:
#Extração de elementos
m = np.array([1,2,3,4,5,6])
#Mostra o elemento na posição 2
print(m[1])
print("------")
#Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("------")
#Mostra o array criadoa partir da 2a posição até todo o restante do array
print(m[1:])
print("------")
#Mostra o array a partir da antepenultima posição até o final
print(m[-3:])

2
------
[1 2]
------
[2 3 4 5 6]
------
[4 5 6]


In [45]:
#Extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("------")
#Primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("------")
#Segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)
print("------")
#Terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)
print("------")
#Todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("------")
#Todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)
print("------")

[[4 5]
 [6 1]
 [7 4]]
------
[4 5]
------
[6 1]
------
[7 4]
------
[4 6 7]
------
[5 1 4]
------


In [47]:
#Adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n+o
print(res1)
print("------")
res2 = n*o
print(res2)
print("------")
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
------
[[1 2]
 [3 4]]
------
[[3 3]
 [5 5]
 [7 7]]


In [48]:
#Transposição, rearranjo um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
#Mostra a matriz transposta entre linha e coluna
print(f)
print("------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [50]:
#Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)
print("------")
#Rearanja um conjunto de 15 elementos
#Mostra a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [52]:
#Expressões lógicas
#Usando where
#Criando matriz com valores positivos e negativos
v = np.random.randn(4,4)
print(v)
#Criando matriz com valores boleanos usando array v
x = (v>0)
print(x)
#Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x>0,1,-1)
print(z)

[[ 1.52162866  0.01966187 -1.11030921 -0.00903099]
 [-1.15512073 -0.5204406  -0.36712587  1.06548005]
 [-0.41034026 -0.4972618   0.61907143 -0.79096294]
 [ 0.84491691 -0.39173945  2.10365249  0.49751156]]
[[ True  True False False]
 [False False False  True]
 [False False  True False]
 [ True False  True  True]]
[[ 1  1 -1 -1]
 [-1 -1 -1  1]
 [-1 -1  1 -1]
 [ 1 -1  1  1]]
